-- Sequences
-- BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE DELIVERY_SEQ'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
CREATE SEQUENCE DELIVERY_SEQ START WITH 1 INCREMENT BY 1;

-- BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE INSPECTION_SEQ'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
CREATE SEQUENCE INSPECTION_SEQ START WITH 1 INCREMENT BY 1;

-- BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE PRICE_HISTORY_SEQ'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
CREATE SEQUENCE PRICE_HISTORY_SEQ START WITH 1 INCREMENT BY 1;

-- BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE ALERT_SEQ'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
CREATE SEQUENCE ALERT_SEQ START WITH 1 INCREMENT BY 1;

-- BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE ACTION_SEQ'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
CREATE SEQUENCE ACTION_SEQ START WITH 1 INCREMENT BY 1;

-- Tables

-- Strong entity, from olist_sellers_dataset.csv
-- BEGIN EXECUTE IMMEDIATE 'DROP TABLE SELLER CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
CREATE TABLE SELLER (
    SellerID VARCHAR2(64) PRIMARY KEY,
    SellerZipCodePrefix VARCHAR2(10),
    SellerCity VARCHAR2(100),
    SellerState VARCHAR2(5)
);

-- Strong entity, from olist_products_dataset.csv
-- BEGIN EXECUTE IMMEDIATE 'DROP TABLE PRODUCT CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
CREATE TABLE PRODUCT (
    ProductID VARCHAR2(64) PRIMARY KEY,
    ProductCategoryName VARCHAR2(100)
);

-- Strong entity, from olist_orders_dataset.csv
-- BEGIN EXECUTE IMMEDIATE 'DROP TABLE PURCHASE_ORDER CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
CREATE TABLE PURCHASE_ORDER (
    PO_ID VARCHAR2(64) PRIMARY KEY,
    OrderDate TIMESTAMP,
    ExpectedDeliveryDate TIMESTAMP,
    OrderStatus VARCHAR2(30)
);

-- Strong entity, pre-seeded
-- BEGIN EXECUTE IMMEDIATE 'DROP TABLE DEFECT_TYPE CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
CREATE TABLE DEFECT_TYPE (
    DefectTypeID NUMBER PRIMARY KEY,
    DefectCategory VARCHAR2(50) NOT NULL,
    SeverityWeight NUMBER(3,1)
);

-- Strong entity, pre-seeded
-- BEGIN EXECUTE IMMEDIATE 'DROP TABLE RISK_WEIGHT_CONFIG CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
CREATE TABLE RISK_WEIGHT_CONFIG (
    WeightConfigID NUMBER PRIMARY KEY,
    ProductCategoryLevel VARCHAR2(100),
    DelayWeight NUMBER(5,2),
    QualityWeight NUMBER(5,2),
    PriceWeight NUMBER(5,2),
    EffectiveFromDate DATE
);

-- Weak entity, owner = PURCHASE_ORDER, from olist_order_items_dataset.csv
-- BEGIN EXECUTE IMMEDIATE 'DROP TABLE PO_LINE CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
CREATE TABLE PO_LINE (
    PO_ID VARCHAR2(64) NOT NULL REFERENCES PURCHASE_ORDER(PO_ID),
    LineNo NUMBER NOT NULL,
    ProductID VARCHAR2(64) REFERENCES PRODUCT(ProductID),
    SellerID VARCHAR2(64) REFERENCES SELLER(SellerID),
    UnitPriceAtOrder NUMBER(10,2),
    FreightValue NUMBER(10,2),
    ShippingLimitDate TIMESTAMP,
    PRIMARY KEY (PO_ID, LineNo)
);

-- 1:1 with PURCHASE_ORDER, derived from orders CSV
-- BEGIN EXECUTE IMMEDIATE 'DROP TABLE DELIVERY CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
CREATE TABLE DELIVERY (
    DeliveryID NUMBER PRIMARY KEY,
    PO_ID VARCHAR2(64) UNIQUE NOT NULL REFERENCES PURCHASE_ORDER(PO_ID),
    DeliveredCarrierDate TIMESTAMP,
    ActualDeliveryDate TIMESTAMP,
    SellerDispatchDelayDays NUMBER(10,2),
    CarrierTransitDelayDays NUMBER(10,2),
    DelayDays NUMBER(10,2)
);

-- from olist_order_reviews_dataset.csv
-- BEGIN EXECUTE IMMEDIATE 'DROP TABLE QUALITY_INSPECTION CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
CREATE TABLE QUALITY_INSPECTION (
    InspectionID NUMBER PRIMARY KEY,
    PO_ID VARCHAR2(64) NOT NULL REFERENCES PURCHASE_ORDER(PO_ID),
    InspectionDate TIMESTAMP,
    ReviewScore NUMBER(1),
    RejectionFlag VARCHAR2(10),
    ReviewAnswerTimestamp TIMESTAMP,
    ReviewCommentTitle VARCHAR2(500),
    ReviewCommentMessage CLOB,
    DefectTypeID NUMBER REFERENCES DEFECT_TYPE(DefectTypeID)
);

-- Weak entity, owner = SELLER
-- BEGIN EXECUTE IMMEDIATE 'DROP TABLE RISK_SCORE CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
CREATE TABLE RISK_SCORE (
    SellerID VARCHAR2(64) NOT NULL REFERENCES SELLER(SellerID),
    EvaluationPeriod VARCHAR2(7) NOT NULL,
    DelaySubScore NUMBER(5,2),
    QualitySubScore NUMBER(5,2),
    PriceVolatilitySubScore NUMBER(5,2),
    WeightedRiskScore NUMBER(5,2),
    RiskTrend VARCHAR2(10),
    RiskCategory VARCHAR2(10),
    PRIMARY KEY (SellerID, EvaluationPeriod)
);

-- Alert Log
-- BEGIN EXECUTE IMMEDIATE 'DROP TABLE ALERT_LOG CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
CREATE TABLE ALERT_LOG (
    AlertID NUMBER PRIMARY KEY,
    SellerID VARCHAR2(64) NOT NULL,
    EvaluationPeriod VARCHAR2(7) NOT NULL,
    AlertDate TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    ThresholdCrossedCategory VARCHAR2(50),
    AlertMessage VARCHAR2(500),
    AlertStatus VARCHAR2(20) DEFAULT 'Open',
    EscalationLevel NUMBER(1) DEFAULT 1,
    FOREIGN KEY (SellerID, EvaluationPeriod) REFERENCES RISK_SCORE(SellerID, EvaluationPeriod)
);

-- Corrective Action
-- BEGIN EXECUTE IMMEDIATE 'DROP TABLE CORRECTIVE_ACTION CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
CREATE TABLE CORRECTIVE_ACTION (
    ActionID NUMBER PRIMARY KEY,
    AlertID NUMBER NOT NULL REFERENCES ALERT_LOG(AlertID),
    ActionDescription VARCHAR2(1000),
    ResponsibleParty VARCHAR2(100),
    TargetResolutionDate DATE,
    ActualResolutionDate DATE,
    ActionStatus VARCHAR2(20) DEFAULT 'Pending',
    ImpactOnNextRiskScore NUMBER(5,2)
);

-- Price History
-- BEGIN EXECUTE IMMEDIATE 'DROP TABLE PRICE_HISTORY CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
CREATE TABLE PRICE_HISTORY (
    PriceRecordID NUMBER PRIMARY KEY,
    SellerID VARCHAR2(64) NOT NULL REFERENCES SELLER(SellerID),
    ProductID VARCHAR2(64) NOT NULL REFERENCES PRODUCT(ProductID),
    PriceDate TIMESTAMP,
    UnitPrice NUMBER(10,2),
    PriceChangePercent NUMBER(8,4)
);

-- Seed Data

INSERT INTO DEFECT_TYPE (DefectTypeID, DefectCategory, SeverityWeight) VALUES (1, 'Late Delivery', 3.0);
INSERT INTO DEFECT_TYPE (DefectTypeID, DefectCategory, SeverityWeight) VALUES (2, 'Damaged Goods', 4.0);
INSERT INTO DEFECT_TYPE (DefectTypeID, DefectCategory, SeverityWeight) VALUES (3, 'Wrong Item', 5.0);
INSERT INTO DEFECT_TYPE (DefectTypeID, DefectCategory, SeverityWeight) VALUES (4, 'Poor Quality', 3.5);
INSERT INTO DEFECT_TYPE (DefectTypeID, DefectCategory, SeverityWeight) VALUES (5, 'Other', 1.0);

INSERT INTO RISK_WEIGHT_CONFIG (WeightConfigID, ProductCategoryLevel, DelayWeight, QualityWeight, PriceWeight, EffectiveFromDate)
VALUES (1, 'DEFAULT', 0.40, 0.35, 0.25, SYSDATE);

COMMIT;
